version: 2.1

# TODO: so are any top level names circle does not use, just ignored?
params:
  deps: &deps
    dependency-file: dev-requirements.txt

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    environment:
      TERM: screen-256color
    steps:
      - checkout
      - python/load-cache:
          <<: *deps
      - python/install-deps:
          <<: *deps
      - python/save-cache:
          <<: *deps
      - run:
          name: Test
          command: inv test
      - run:
          name: Lint
          command: flake8

workflows:
  main:
    jobs:
      - build
