version: 2.1

orbs:
  orb: invocations/orb@1.6.0

workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/coverage:
          name: Test
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test"]
          matrix:
            parameters:
              version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
